<?php
/**
 * Main template, content is generated by other views
 *
 * Variables that must be defined :
 *      $title string : title of the page
 *      $content string : content of the page
 */
?>

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $title ?></title>
    <link rel="stylesheet" href="./css/style.css">
</head>

<body>
    <header>
        <nav>

        </nav>
    </header>

    <main>
        <?= $content ?>
    </main>

    <footer>

    </footer>

</body>
</html>

